config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/team'
  post 'home/team', to: "home#team"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common_content, only: [:index, :team]

  def common_content
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @corp_power = Faker::Company.bs
    @corp_title = Faker::Company.profession

    @rand_num = rand(1..1000)
    @set_number = rand(1..4)

    @avatar = Faker::Avatar.image(slug: @rand_num, size: "200x200", format: "png", set: "set#{@set_number}", bgset: "bg1")
  end

  def index

  end

  def show
    @count = 0
    @team_number.times do
    @rand_num = rand(1..1000)
    @set_number = rand(1..4)
    @count += 1
  end


  def team
    @team_number = params[:team_number].to_i
    @count = 0
    @rand_num = rand(1..1000)
    @set_number = rand(1..4)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.html.erb
<div class="card">

  <div class="row no-gutters">
    <div class="col-md-4 mt-2 rounded-circle" style="text-align: center;">

      <%= form_tag home_team_path, :method => 'POST' do %>
            <%= select_tag(:team_number, options_for_select([
                         ['0', 0],
                         ['1', 1],
                         ['2', 2],
                         ['3', 3],
                         ['4', 4],
                         ['5', 5],
                         ['6', 6],
                         ['7', 7],
                         ['8', 8],
                         ['9', 9],
                         ['10', 10],
                         ])) %>
        <%= submit_tag "Build your team", class: "btn btn-primary" %>
    <% end %>
    </div>
      <div class="col-md-8">
        <div class="card-body">

        </div>
      </div>

  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Super Hero Generator", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
      <form class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li> <%= link_to "Team Page", home_team_path, class: "nav-link" %> </li>
          <li> <%= link_to "Create a Team", home_team_path, class: "nav-link" %> </li>

        </ul>
      </form>
    </div>
  </div>
</nav>

app/views/home/_show_team.html.erb
<br>


  <div class="row no-gutters">

    <div class="col-md-4 mt-2 rounded-circle" style="text-align: center;">
      <%= image_tag Faker::Avatar.image(slug: @rand_num, size: "200x200", format: "png", set: "set#{@set_number}", bgset: "bg1"), alt: "alttext", size: "300x300" %>
    </div>
      <div class="col-md-8">
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p class="card-text">Your super hero name: # <%= @count  %> <strong><%= Faker::Superhero.name %></strong></p>
            <p class="card-text"> Your super hero power: <cite class="text-info"> <%= Faker::Superhero.power %> </cite>  </p>

            <hr class="my-4">

            <p class="card-text"> Your super corp power: <cite class="text-info"> <%= Faker::Company.bs %> </cite>  </p>

            <hr class="my-4">

            <p class="card-text"> Your super corp title: <cite class="text-info"> <%= Faker::Company.profession %> </cite>  </p>

            <hr class="my-4">

            <footer class="blockquote-footer">Remember all of this is fake.👻</footer>
          </blockquote>
        </div>
      </div>
            <br>

  </div>
<% end %>

app/views/home/index.html.erb
<br>
<div class="card mb-3" style="max-width: 740px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="..." class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"> <%=  @hero_name %> </h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-header">
    <h5> <%= @hero_name %> </h5>
  </div>
  <div class="row no-gutters">

    <div class="col-md-4 mt-2 rounded-circle" style="text-align: center;">
      <%= image_tag @avatar, alt: "alttext", size: "300x300" %>
    </div>
      <div class="col-md-8">
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p class="card-text">Your super hero name: <strong><%= @hero_name %></strong></p>
            <p class="card-text"> Your super hero power: <cite> <%= @hero_power %> </cite>  </p>

            <hr class="my-4">

            <p class="card-text"> Your super corp power: <cite> <%= @corp_power %> </cite>  </p>

            <hr class="my-4">

            <p class="card-text"> Your super corp title: <cite> <%= @corp_title %> </cite>  </p>

            <hr class="my-4">

            <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
          </blockquote>
        </div>
      </div>
  </div>
  <div class="card-footer">
    <h5> <%=   %> </h5>
  </div>
</div>

app/views/home/team.html.erb
<br>

<div class="card">

    <div class="card-header">
      <h5> <%= @team_number > 0 ? "#{@team_number} super heros..." : "How many team members do you need?" %>   </h5>
    </div>

      <% if @team_number > 0 %>
        <%= render "home/show_team" %>
      <% else %>
        <%= render "home/create_team" %>
      <% end %>
    <div class="card-footer w-100">

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render "home/navbar" %>
  <body>
    <div class="container">
      <%= yield %>
      <br><br>
      <center>
        Copyright Dom Lizarraga - All Rights Reserved 😜
      </center>
    </div>
  </body>
</html>